version: '3'
services:
  app:
    env_file:
      - docker/env
    build:
      context: .
      dockerfile: docker/rails/Dockerfile
    command: bundle exec puma -C ./docker/rails/puma.rb
    volumes:
      - .:/myapp
      - ./config/application.yml:/myapp/config/application.yml
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    depends_on:
      - db
      - redis
    expose:
      - "8082"
    tty: true
    stdin_open: true

  db:
    restart:
      always
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - db-data:/var/lib/mysql
    ports:
      - 43306:3306

  web:
    image: nginx:1.13.5-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - public-data:/myapp/public
    ports:
      - 8082:80
    depends_on:
      - app

  redis:
    image: redis:3.2.4-alpine
    ports:
      - 46379:6379

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
